
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'C368F8BD47A14FA860E3C9C21EC53558'
    
_lr_action_items = {'AND':([1,2,4,5,6,7,10,11,12,14,15,19,20,21,22,23,25,26,],[-9,-4,17,-3,-5,-7,-1,-8,-2,-6,17,17,17,17,17,17,17,-12,]),'R_BRACKET':([1,2,5,6,7,10,11,12,14,15,19,20,21,22,25,26,],[-9,-4,-3,-5,-7,-1,-8,-2,-6,-11,-13,-10,-15,-14,26,-12,]),'OR':([1,2,4,5,6,7,10,11,12,14,15,19,20,21,22,23,25,26,],[-9,-4,16,-3,-5,-7,-1,-8,-2,-6,16,16,16,16,16,16,16,-12,]),'L_BRACKET':([8,],[18,]),'EG':([0,3,9,13,16,17,18,24,],[3,3,3,3,3,3,3,3,]),'TRUE':([0,3,9,13,16,17,18,24,],[6,6,6,6,6,6,6,6,]),'EU':([0,3,9,13,16,17,18,24,],[8,8,8,8,8,8,8,8,]),'EXCLAMATION':([0,3,9,13,16,17,18,24,],[9,9,9,9,9,9,9,9,]),'AP':([0,3,9,13,16,17,18,24,],[10,10,10,10,10,10,10,10,]),'$end':([1,2,4,5,6,7,10,11,12,14,15,19,20,21,22,26,],[-9,-4,0,-3,-5,-7,-1,-8,-2,-6,-11,-13,-10,-15,-14,-12,]),'EX':([0,3,9,13,16,17,18,24,],[13,13,13,13,13,13,13,13,]),'FALSE':([0,3,9,13,16,17,18,24,],[14,14,14,14,14,14,14,14,]),'UNTIL':([1,2,5,6,7,10,11,12,14,15,19,20,21,22,23,26,],[-9,-4,-3,-5,-7,-1,-8,-2,-6,-11,-13,-10,-15,-14,24,-12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'not':([0,3,9,13,16,17,18,24,],[7,7,7,7,7,7,7,7,]),'and':([0,3,9,13,16,17,18,24,],[1,1,1,1,1,1,1,1,]),'eu':([0,3,9,13,16,17,18,24,],[2,2,2,2,2,2,2,2,]),'or':([0,3,9,13,16,17,18,24,],[11,11,11,11,11,11,11,11,]),'ex':([0,3,9,13,16,17,18,24,],[12,12,12,12,12,12,12,12,]),'formula':([0,3,9,13,16,17,18,24,],[4,15,19,20,21,22,23,25,]),'eg':([0,3,9,13,16,17,18,24,],[5,5,5,5,5,5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> formula","S'",1,None,None,None),
  ('formula -> AP','formula',1,'p_formula_ap','parser.py',20),
  ('formula -> ex','formula',1,'p_formula_ex','parser.py',26),
  ('formula -> eg','formula',1,'p_formula_eg','parser.py',31),
  ('formula -> eu','formula',1,'p_formula_eu','parser.py',36),
  ('formula -> TRUE','formula',1,'p_formula_true','parser.py',41),
  ('formula -> FALSE','formula',1,'p_formula_false','parser.py',46),
  ('formula -> not','formula',1,'p_formula_not','parser.py',51),
  ('formula -> or','formula',1,'p_formula_or','parser.py',56),
  ('formula -> and','formula',1,'p_formula_and','parser.py',61),
  ('ex -> EX formula','ex',2,'p_ex','parser.py',68),
  ('eg -> EG formula','eg',2,'p_eg','parser.py',73),
  ('eu -> EU L_BRACKET formula UNTIL formula R_BRACKET','eu',6,'p_eu','parser.py',78),
  ('not -> EXCLAMATION formula','not',2,'p_not','parser.py',84),
  ('and -> formula AND formula','and',3,'p_and','parser.py',89),
  ('or -> formula OR formula','or',3,'p_or','parser.py',94),
]
